matrix:
  include:

    - language: python
     python:
      - "3.4"

      before_script:
        - cd server/
      install:
        - pip install -r requirements.txt
      script:
        - pytest
        - python -m unittest discover
        - python -m venv venv/bin/activate

    - language: c
      sudo: false
      before_script:
        - cd arduino
      before_install:
        - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
      cache:
        directories:
         - ~/arduino_ide
         - ~/.arduino15/packages/
      install:
        - arduino --install-library "Adafruit ILI9341","Adafruit GFX Library"
      script:
        - build_main_platforms


    - language: swift
      xcode_project: CarInterface.xcodeproj
      xcode_scheme: CarInterfaceTests
      xcode_destination: platform=iOS Simulator,OS=10.1,name=iPad Pro (9.7-inch)
