matrix:
  include:
    - language: python
      python: 3.6
      before_install:
        - cd server/
      install:
        - pip install -r requirements.txt
      script:
        - python -m py_compile main.py

    - language: c
      before_script:
        - cd arduino/
      before_install:
        - source <(curl -SLs https://raw.githubusercontent.com/platisd/travis-ci-arduino/master/install.sh)
      install:
        - arduino --install-library "Smartcar shield"
      script:
        - build_platform mega2560
      cache:
        directories:
          - ~/arduino_ide
          - ~/.arduino15/packages/

deploy:
  provider: releases
  api_key:
    secure: bdeac7bd7ffa0b46a10afbc198cdd6254d2cc6d1
  file:
    - $ARDUINO_HEX_DIR/mega2560/testCar/testCar.ino.hex
    - $ARDUINO_HEX_DIR/mega2560/testCar/testCar.ino.with_bootloader.hex
    - $ARDUINO_HEX_DIR/mega2560/obstacleAvoidance/obstacleAvoidance.ino.hex
    - $ARDUINO_HEX_DIR/mega2560/obstacleAvoidance/obstacleAvoidance.ino.with_bootloader.hex
  skip_cleanup: true
  on:
    tags: true
