matrix:
  include:
    - language: python
      python: 3.6
      before_install:
        - cd server/
      install:
        - pip install -r requirements.txt
      script:
        - python -m py_compile main.py

    - language: c
      before_script:
        - cd arduino/
      before_install:
        - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
      install:
        - arduino --install-library "Smartcar shield"
      script:
        - build_platform mega2560
      cache:
        directories:
          - ~/arduino_ide
          - ~/.arduino15/packages/

    - language: swift
      os: osx
      osx_image: xcode10.3
      before_script:
        - cd app
      script:
        - xcodebuild clean test -project CarInterface.xcodeproj -scheme CarInterface -destination "platform=iOS Simulator,name=iPhone 7,OS=11.4" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
